[project]
name = "natyra"
version = "2.9.3"
description = "A command-line app for downloading Apple Music songs, music videos and post videos."
readme = "README.md"
license = "MIT"
requires-python = ">=3.10"
dependencies = [
    "async-lru>=2.0.5",
    "fastapi>=0.136.1",
    "httpx>=0.28.1",
    "m3u8>=6.0.0",
    "mutagen>=1.47.0",
    "pillow>=12.0.0",
    "pydantic-settings>=2.14.1",
    "pywidevine>=1.8.0",
    "uvicorn>=0.46.0",
    "yt-dlp>=2025.10.22",
]

[project.urls]
Repository = "https://github.com/glomatico/natyra"


